webserver:
  port: 80

hostname:
  city: "*.weareroots.org"
  website: "weareroots.org"

# Google Analytics key
ga: "UA-xxxxxx-2"

logger:
  # Log Levels:
  # SEVERE: 1000
  # WARN:   800
  # INFO:   600
  # FINE:   400
  # FINER:  200
  # FINEST: 100
  level: 200
  syslog: false
  file: false
  console: true
  filename: "./logs/app.log"

data:
  city:
    - name: "Thessaloniki"
    headerTitle: "ΘΕΣΣΑΛΟΝΙΚΗ"
    hostname: "www.thesact.gr"
    domainName: "thesact.gr"
    twitter: "SKG_Tech"
#    Thessact GCalendar keys
#    calendarUrl: "37olphqpei4cvuqn3a2ik462sk@group.calendar.google.com"
#    calendarApiKey: "AIzaSyBUra36HNU0Gjw3ywcGNSLDbpzubHY516U"
    calendarUrl: "2ul10sd9g30mnk1vpmcnnp5qv4@group.calendar.google.com"
    calendarApiKey: "AIzaSyC75rnKyEkGxmVyG7hlqFicwPBgDmQLN_w"
    lang: "gr"
    calendarStyle: "roots"
    coverImage: "/assets/city-headers/thessaloniki.jpg"
    coverImageSm: "/assets/city-headers/thessaloniki-sm.jpg"
    curators:
      - name: "Thanasis Polychronakis"
      email: "thanpolas@gmail.com"
      - name: "Theodore Keloglou"
      email: "theodorekeloglou@gmail.com"
      - name: "Kostas Bariotis"
      email: "konmpar@gmail.com"
    og:
      title: "Thessaloniki Grassroot Communities"
      siteName: "thessact"
      url: "www.thesact.gr"
      description: "Thessaloniki Grassroot Communities"
      image: ""
      appId: ""
      type: "website"
    ga: "UA-41787746-7"
    - name: "Athens"
    headerTitle: "ΑΘΗΝΑ"
    hostname: "ath.weareroots.org"
    domainName: "weareroots.org"
    calendarUrl: "2ul10sd9g30mnk1vpmcnnp5qv4@group.calendar.google.com"
    calendarApiKey: "AIzaSyC75rnKyEkGxmVyG7hlqFicwPBgDmQLN_w"
    lang: "gr"
    calendarStyle: "google"
    coverImage: "/assets/city-headers/athens.jpg"
    coverImageSm: "/assets/city-headers/athens-sm.jpg"
    curators:
      - name: "Thanasis Polychronakis"
      email: "thanpolas@gmail.com"
      - name: "Theodore Keloglou"
      email: "theodorekeloglou@gmail.com"
      - name: "Kostas Bariotis"
      email: "konmpar@gmail.com"
    og:
      title: "Athens Grassroot Communities"
      siteName: "Athensact"
      url: "ath.thesact.gr"
      description: "Athens Grassroot Communities"
      image: ""
      appId: ""
      type: "website"
    ga: "xxx"

